#
# Blog Settings
#
author: Ignacio Fuentes
description: My thoughts on Software Development
url: http://www.ignaciofuentes.com
disqus_short_name: ignaciofuentes
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: 


#
# Jekyll Settings
#
markdown: redcarpet
pygments: true
permalink: /archive/:year/:month/:day/:title/
paginate: 20
paginate_path: "page/:num"
category_dir: categories
