#
# Blog Settings
#
author: Ignacio Fuentes
description: My thoughts on Software Development
url: http://ignaciofuentes.com
title: ignaciofuentes

gravatar_url: https://2.gravatar.com/avatar/7fc56bb23fe5236b432b5b91597109a1
subscribe_rss: http://feeds.ignaciofuentes.com/ignaciofuentes

# Github repositories
github_user: ignaciofuentes
github_repo_url: https://github.com/ignaciofuentes/ignaciofuentes.github.io/

# Twitter
twitter_user: ignacioafuentes
twitter_tweet_button: true

# Disqus Comments
disqus_short_name: ignaciofuentes
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: 


#
# Jekyll Settings
#
markdown: redcarpet
pygments: true
permalink: /archive/:year/:month/:day/:title/
paginate: 20
paginate_path: "page/:num"
category_dir: categories
